#!/usr/bin/bash

# Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    echo "PYFILE environment variable is not set."
    exit 1
fi

# Run the Python script using the value of PYFILE
python3 "$PYFILE"